### ISSUE TITLE
Current master branch fails pylint check

### ISSUE THREAD

**Issue by peteeckel** [m-erhardt/check-synology-plugins#6]
I just wanted to submit a PR but can't, because the pylint check fails.

Though I'd love to fix it, the issue is with the current master branch and not my PR - so I assume this is a separate issue altogether.

**Comment by m-erhardt** [comment]
Thanks for your PR! IPv6 support is definitely a useful addition.

I agree, the failing pylint check is certainly not your fault 😉.
This simply happened due to added/changed rules within a newer version of pylint.

Looking at pylint's issue tracker there are still lot's of false positives and edge-cases around the `used-before-assignment` check.
I've silenced this for now by adding `# pylint: disable=used-before-assignment`to the relevant lines.
Feel free to rebase your PR to the new commit on the master branch.

I'll think about a more elegant way to solve this in the future...

**Comment by peteeckel** [comment]
Hi @m-erhardt, unfortunately now pycodestyle barfs ... 

```
pete@lagavulin check-synology-plugins % pycodestyle ./*.py --max-line-length=100
./check_synology_cpu.py:185:58: E261 at least two spaces before inline comment
./check_synology_cpu.py:189:80: E261 at least two spaces before inline comment
./check_synology_cpu.py:189:101: E501 line too long (120 > 100 characters)
./check_synology_ram.py:189:66: E261 at least two spaces before inline comment
./check_synology_ram.py:189:101: E501 line too long (106 > 100 characters)
```
